{{- if .Values.rbac.role.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.role.name }}
  namespace: {{ .Release.Namespace }}
rules:
{{- toYaml .Values.rbac.role.rules | nindent 2 }}
{{- end }}

